### ISSUE TITLE
[Hacktoberfest] Add more misc command(s)

### ISSUE THREAD

**Issue by albertopoljak** [Tortoise-Community/Tortoise-BOT#147]
Add any misc command, simple or complex, that you'd like.

You can find the cog in `/cogs/misc.py` and there are already some commands there like ping, status, pfp, shoot, throw etc from which you can get general idea on what you could add.

**Comment by MufaddalHakim** [comment]
where is the discord link?

**Comment by ryuga** [comment]
https://discord.gg/WeUtJ7hqum

**Comment by JohanSanSebastian** [comment]
#165 - Added a server info command

**Comment by ryuga** [comment]
Hii. I just saw your commit. Anyway you could integrated that to work with our embed handler?

**Comment by JohanSanSebastian** [comment]
Sure let me have a look!

**Comment by JohanSanSebastian** [comment]
Hey @ryuga ,
I had a look at the embed_handler.py file and wanted to ask if I could add a new custom embed for the server info.

**Comment by ryuga** [comment]
Yeah sure. go ahead.

**Comment by JohanSanSebastian** [comment]
Hey @ryuga ,
I have done all the changes requested.
#165
