### ISSUE TITLE
KICK and BAN commands not working

### ISSUE THREAD

**Issue by ryuga-hideki** [Tortoise-Community/Tortoise-BOT#28]
The command displays the preset embed on #deterrence-log channel but doesn't execute the function.

**Comment by albertopoljak** [comment]
Kick is working but ban has the following exception:
```
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.description: Could not interpret "['**TYPE:** Ban\n**REASON:** Testing the bot\n**DURATION:** Permanent', '\nIf this happened by a mistake contact moderators.']" as string.
```

Due to the ban command needing rewrite will close this and move to #29

**Comment by ryuga-hideki** [comment]
ban command not working (not tested kick)
