### ISSUE TITLE
Integrate Mod mail with the API and add Logging 

### ISSUE THREAD

**Issue by ryuga-hideki** [Tortoise-Community/Tortoise-BOT#45]
And channels should be configured correctly

**Comment by albertopoljak** [comment]
To elaborate more:
Integrate modmail with API - aka set field `modmail` from mod-mail user to True/False accordingly.
Mod-mail logging - keep track of mod-mail messages and upon completition send track as file to private discord channel.
Bonus: Refactor modmail cog - unverified users should only be able to use modmail in DM options.

**Comment by albertopoljak** [comment]
Log done 5202f4e

**Comment by albertopoljak** [comment]
Closing due to lack of information.

Integrate modmail with API - unclear how to do it with current DM system as there is no guild ID in DMS yet API requires guild_id key.

The bonus part should be it's own issue.

Open new issue if new information arries.
