### ISSUE TITLE
[Unknown] Create comand to list all pending mod-mails? Or have the bot remember message ids it sends to channel (messages like `user submitted mod mail request`) then delete those as mods accept them?

### ISSUE THREAD

**Issue by albertopoljak** [Tortoise-Community/Tortoise-BOT#49]
Delete message saying 'user submitted mod mail request' after it's accepted by admin? Or
just add a command to list current pending ones? Or something else?

**Comment by ryuga-hideki** [comment]
The mod mail is has separate individual bool fields in the user row, so it just need to be set to true in case of future commands to see the pending mod mails
