### ISSUE TITLE
Remove verification for ping socket endpoint

### ISSUE THREAD

**Issue by albertopoljak** [Tortoise-Community/Tortoise-BOT#52]
System was not designed to have endpoints without verification process, so this request might be a hassle maybe even unnecessary.

**Comment by albertopoljak** [comment]
Referencing  838edc0

**Comment by ryuga-hideki** [comment]
This issue was left out unattended even after implementation.

**Comment by albertopoljak** [comment]
> 
> 
> Referencing [838edc0](https://github.com/Tortoise-Community/Tortoise-BOT/commit/838edc026a14fcc50dca2c45c93f0c564052309c)

Because the fix is temporal.
