### ISSUE TITLE
Notify of our paste service if message is too long

### ISSUE THREAD

**Issue by albertopoljak** [Tortoise-Community/Tortoise-BOT#62]
We have a paste service https://paste.tortoisecommunity.ml
If the message is too long just send a nice message notifying the user that it is too long and they should use our paste instead.

Bonus: 

-  [x] Check if the message is code related

- [X] - Bot will send nice embed message.

**Comment by albertopoljak** [comment]
For idea/inspiration https://github.com/python-discord/bot/blob/master/bot/cogs/bot.py#L219

**Comment by ryuga** [comment]
Code detection is implemented. Bot will now converted the code related long messages into pastes. Closing this issue.
