### ISSUE TITLE
Fix how RTL languages are being displayed in system messages

### ISSUE THREAD

**Issue by hematogender** [Tortoise-Community/Tortoise-BOT#66]
Somewhat related to #65 

If RTL text is present in system messages, it should save LTL position. I suppose this is the right way to deal with it? Here's an example:
![image](https://user-images.githubusercontent.com/46577620/79844150-f88be300-83c3-11ea-9f4a-6c6b7ce11fa5.png)

**Comment by albertopoljak** [comment]
Should be fixed in standardized layout #65
