### ISSUE TITLE
Server function improvement

### ISSUE THREAD

**Issue by ryuga-hideki** [Tortoise-Community/Tortoise-BOT#73]
- [ ] Changing timed custom statuses for the bot + integrate with API

-  [ ] The event submissions, the mod mail and the bug report should have an option to be turned off. + integrate with API (all the above mentioned improvements comes under the server utils endpoint)

-  [ ] The modmail should be integrated with the api (save cache to API)
-  [ ]  Adding strikes to API #80 
-  [X] Adding warnings API

**Comment by albertopoljak** [comment]
Update the comment as it was unformatted.

**Comment by ryuga-hideki** [comment]
New issues would be opened individually for all these.
